version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  target-branch: "/update-dep"
  ignore:
  - dependency-name: xo
    versions:
    - 0.37.1
    - 0.38.1
    - 0.38.2
  - dependency-name: atom-package-deps
    versions:
    - 7.1.0
    - 7.2.0
    - 7.2.1
    - 7.2.2
  - dependency-name: electron-rebuild
    versions:
    - 2.3.4
