os:
  - linux
  - osx
language: node_js
node_js:
  - '12'
  - '10'
env:
  global:
    - CC=clang
    - CXX=clang++
    - APM_TEST_PACKAGES=""
    - ATOM_LINT_WITH_BUNDLED_NODE="true"
  matrix:
    - ATOM_CHANNEL=stable

install: false
script:
  - chmod u+x ./script/build-package.sh
  - ./script/build-package.sh
  - npm run test
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
    - update-dev
addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
