os:
  - linux
  - osx
  # - windows
language: node_js
node_js:
  - '12'
  - '10'
env:
  global:
    - CC=clang
    - CXX=clang++
    - ATOM_LINT_WITH_BUNDLED_NODE="true"
    - ATOM_CHANNEL="stable"
    # - APM_TEST_PACKAGES=""

before_install:
  - chmod u+x ./script/build-atom.sh
  - . ./script/build-atom.sh
install:
  - chmod u+x ./script/build-package.sh
  - . ./script/build-package.sh
script:
  - chmod u+x ./script/build-rebuild.sh
  - . ./script/build-rebuild.sh
  - chmod u+x ./script/build-spec.sh
  - . ./script/build-spec.sh
  - npm run test
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
    - update-dep
addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
