os:
  - linux
language: node_js
node_js:
  - '12'
  - '10'
env:
  global:
    - CC=clang
    - CXX=clang++
install:
  - chmod u+x ./script/build-package.sh
  - ./script/build-package.sh
script:
  - npm run test
addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - git
    - libsecret-1-dev
